# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 01:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('total_session_count', models.BigIntegerField(default=0)),
                ('total_fav', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 13, 1, 21, 35, 713619, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 13, 1, 21, 35, 713677, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Favs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.IntegerField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ommm.Exercises')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('heartbeat', models.IntegerField(null=True)),
                ('feeling', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ommm.Exercises')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.CharField(max_length=128)),
                ('animation_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=128, null=True)),
                ('housing', models.CharField(max_length=128, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('card_number', models.CharField(max_length=128, null=True)),
                ('date_subscribing', models.DateTimeField(editable=False, null=True)),
                ('health_level', models.IntegerField(default=10)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ommm.Subscriptions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sessions',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ommm.ValidatedUser'),
        ),
        migrations.AddField(
            model_name='favs',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ommm.ValidatedUser'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ommm.Tags'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ommm.Types'),
        ),
    ]
