# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ommm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favs',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='favs',
            name='users',
        ),
        migrations.AddField(
            model_name='exercises',
            name='exercise_favs',
            field=models.ManyToManyField(null=True, related_name='user_favs', to='ommm.ValidatedUser'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 13, 17, 40, 23, 993266, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_exercises', to='ommm.Tags'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_exercises', to='ommm.Types'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 13, 17, 40, 23, 993308, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Favs',
        ),
    ]
