# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ommm', '0002_auto_20161213_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 15, 10, 17, 21, 736557, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 15, 10, 17, 21, 736620, tzinfo=utc)),
        ),
    ]
